---
- name: Gather and Display FortiOS Facts
  hosts: fortios
  connection: network_cli
  gather_facts: no
  
  tasks:
  -  name: Gather fortios_facts
     fortios_facts:
       gather_subset:
         - fact: system_status_select
    
  -  name: Print results of fortios_facts
     debug:
      msg: "{{ system_status_select }}"
