---
- name: Change hostname to Inventory hostname
  hosts: ios
  become_method: enable
  become: yes
  connection: network_cli
  gather_facts: no
  
  tasks:
  - name: configure hostname
    ios_config:
      authorize: true
      lines: net_hostname {{ inventory_hostname }}
