---
- name: Change hostname to Inventory hostname
  hosts: ios
  become: yes
  become_method: enable
  connection: network_cli
  gather_facts: no

    - name: configure hostname
      ios_config:
        provider:
          authorize: true
        lines: net_hostname {{ inventory_hostname }}
