---
- name: Change hostname to Inventory hostname
  hosts: ios
  become: yes
  become_method: enable
  connection: network_cli
  gather_facts: no

  tasks:
    - name: configure hostname
      ios_config:
        lines: net_hostname {{ inventory_hostname }}
