---
- name: Change hostname to Inventory hostname
  hosts: ios
  become_method: enable
  connection: network_cli
  gather_facts: no
  
  tasks:
  - name: configure hostname
    ios_config:
      authorize:
      lines: hostname {{ inventory_hostname }}
