---
- name: Change Hostname to Inventory Hostname
  hosts: ios
  connection: network_cli
  gather_facts: no
  
  tasks:
    - name: configure hostname
      provider:
        authorize: yes
      ios_config:
        lines: ansible_net_hostname "{{ inventory_hostname }}"
