---
- name: Change hostname to Inventory hostname
  hosts: ios
  become_method: enable
  connection: local
  gather_facts: no
  
  tasks:
  - name: enter enable mode
      provider:
        authorize: yes

  - name: configure hostname
    ios_config:
      lines: hostname {{ inventory_hostname }}
